# Default values for k8s-janitor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

k8sjanitor:
  aws:
    s3BucketRegion: ""
    s3BucketNameConfigMap: ""
  configMapFileName: ""
  kafka:
    bootstrapServers: ""
    brokerVersionFallback: "0.10.0.0"
    apiVersionFallBack: "0"
    consumerGroupId: "k8s-janitor"
    autoCommit: "false"
    saslMechanisms: ""
    securityProtocol: ""

replicaCount: 1

global:
  labels:
    department: devex
    project: selfservice
image:
  repository: 579478677147.dkr.ecr.eu-central-1.amazonaws.com/ded/k8s-janitor
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "$(Build.BuildId)"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

healthCheck:
  enabled: "true"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

priorityClass:
  enabled: true
  name: selfservice

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true

# resources: {}
resources:
  requests:
    memory: "200Mi"
    cpu: "100m"
  limits:
    memory: "400Mi"
    cpu: "200m"
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
