---
name: $(Build.BuildId)
pool:
  vmImage: 'ubuntu-16.04'
trigger:
  - master
pr: none
steps:
  - bash: |
      set -eu -o pipefail
      sudo pip install awscli
      export AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY)
      export DOCKER_PASSWORD=$(DOCKER_PASSWORD)
      chmod +x ./pipeline.sh
      ./pipeline.sh $(Build.BuildId) $(System.DefaultWorkingDirectory)
      dotnet tool install dotnet-reportgenerator-globaltool --tool-path . --version 4.0.5
      ./reportgenerator "-reports:$(System.DefaultWorkingDirectory)/output/coverage.cobertura.xml" "-targetdir:$(System.DefaultWorkingDirectory)/output" "-reporttypes:HTMLInline;HTMLChart"
      rm -f "$(System.DefaultWorkingDirectory)/output/index.html"
    displayName: Pipeline Bash Script
    enabled: true

  - task: PublishTestResults@2
    displayName: Publish Test Results
    inputs:
      testRunner: VSTest
      testResultsFiles: testresults.trx
      searchFolder: '$(System.DefaultWorkingDirectory)/output'
    condition: succeededOrFailed()

  - task: PublishCodeCoverageResults@1
    displayName: 'Publish code coverage'
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/output/coverage.cobertura.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/output'

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact: manifests"
    inputs:
      PathtoPublish: k8s
      ArtifactName: manifests

  - task: Kubernetes@1
    inputs:
      connectionType: 'Kubernetes Service Connection'
      command: 'rollout'
      arguments: 'status deployment k8s-janitor --timeout=120s'