---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rolemapper-service
  namespace: $(kubernetes-namespace)
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rolemapper-service
  template:
    metadata:
      labels:
        app: rolemapper-service
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
    spec:
      serviceAccountName: rolemapper-sa
      containers:
        - name: rolemapper-service
          image: 579478677147.dkr.ecr.eu-central-1.amazonaws.com/ded/rolemapper-service:$(Build.BuildId)
          ports:
            - containerPort: 80
              name: web
            - containerPort: 8080
              name: metrics
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            httpGet:
              port: web
              path: /healthz
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            httpGet:
              port: web
              path: /healthz
          env:
            - name: S3_AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: dfds-oxygen-k8s-turing-configmap-bucket-binding
                  key: S3_REGION
            - name: S3_AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: dfds-oxygen-k8s-turing-configmap-bucket-binding
                  key: S3_AWS_ACCESS_KEY_ID
            - name: S3_AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: dfds-oxygen-k8s-turing-configmap-bucket-binding
                  key: S3_AWS_SECRET_ACCESS_KEY
            - name: AWS_S3_BUCKET_NAME_CONFIG_MAP
              valueFrom:
                secretKeyRef:
                  name: dfds-oxygen-k8s-turing-configmap-bucket-binding
                  key: BUCKET_NAME
            - name: CONFIG_MAP_FILE_NAME
              value: $(CONFIG_MAP_FILE_NAME)
            - name: KUBERNETES_SERVICE_KAFKA_BOOTSTRAP_SERVERS
              value: $(KUBERNETES_SERVICE_KAFKA_BOOTSTRAP_SERVERS)
            - name: KUBERNETES_SERVICE_KAFKA_BROKER_VERSION_FALLBACK
              value: "0.10.0.0"
            - name: KUBERNETES_SERVICE_KAFKA_API_VERSION_FALLBACK_MS
              value: "0"
            - name: KUBERNETES_SERVICE_KAFKA_SASL_USERNAME
              value: $(KUBERNETES_SERVICE_KAFKA_SASL_USERNAME)
            - name: KUBERNETES_SERVICE_KAFKA_SASL_PASSWORD
              value: $(KUBERNETES_SERVICE_KAFKA_SASL_PASSWORD)
            - name: KUBERNETES_SERVICE_KAFKA_GROUP_ID
              value: "$(KUBERNETES_SERVICE_KAFKA_GROUP_ID)"
            - name: KUBERNETES_SERVICE_KAFKA_ENABLE_AUTO_COMMIT
              value: "false"
            - name: KUBERNETES_SERVICE_KAFKA_SASL_MECHANISMS
              value: "PLAIN"
            - name: KUBERNETES_SERVICE_KAFKA_SECURITY_PROTOCOL
              value: "SASL_SSL"
