---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rolemapper-service
  namespace: $(kubernetes-namespace)
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rolemapper-service
  template:
    metadata:
      labels:
        app: rolemapper-service
    spec:
      serviceAccountName: rolemapper-sa
      containers:
        - name: rolemapper-service
          image: 579478677147.dkr.ecr.eu-central-1.amazonaws.com/ded/rolemapper-service:$(Build.BuildId)
          ports:
            - containerPort: 80
              name: web
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          env:
            - name: AWS_REGION
              value: $(AWS_REGION)
            - name: S3_AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: rolemapper-service
                  key: s3-aws-access-key-id
            - name: S3_AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: rolemapper-service
                  key: s3-aws-secret-access-key
            - name: AWS_S3_BUCKET_NAME_CONFIG_MAP
              valueFrom:
                secretKeyRef:
                  name: rolemapper-service
                  key: s3-bucket-name
