apiVersion: v1
kind: Namespace
metadata:
  name:  selfservice

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-janitor-sa
  namespace: selfservice

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-janitor-configmap-updater
rules:
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["create"]
- apiGroups: ["","extensions","apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["*"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-janitor-configmap-updater-binding
subjects:
  - kind: ServiceAccount
    name: k8s-janitor-sa
    namespace: selfservice
roleRef:
  kind: ClusterRole
  name: k8s-janitor-configmap-updater
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read-namespaces
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch

# Workaround to allow K9s to list pods at all
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: iamrole-to-clusterrole-binding
subjects:
  - kind: Group
    name: DFDS-ReadOnly
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: read-namespaces
  apiGroup: rbac.authorization.k8s.io