apiVersion: v1
kind: Namespace
metadata:
  name:  selfservice

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: rolemapper-sa
  namespace: selfservice

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rolemapper-configmap-updater
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["aws-auth"]
  verbs: ["update", "get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rolemapper-configmap-updater-binding
subjects:
  - kind: ServiceAccount
    name: rolemapper-sa
    namespace: selfservice
roleRef:
  kind: ClusterRole
  name: rolemapper-configmap-updater
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: iamrole-to-clusterrole-binding
subjects:
  - kind: Group
    name: DFDS-ReadOnly
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io