apiVersion: v1
kind: Secret
metadata:
  name: k8s-janitor
  namespace: $(kubernetes-namespace)
type: Opaque
stringData:
  s3-bucket-name: "$(AWS_S3_BUCKET_NAME_CONFIG_MAP)"
  s3-aws-access-key-id: "$(S3_AWS_ACCESS_KEY_ID)"
  s3-aws-secret-access-key: "$(S3_AWS_SECRET_ACCESS_KEY)"

---
apiVersion: v1
kind: Secret
metadata:
  name: k8s-janitor-kafka-credentials
  namespace: $(kubernetes-namespace)
type: Opaque
stringData:
  username: "$(KUBERNETES_SERVICE_KAFKA_SASL_USERNAME)"
  password: "$(KUBERNETES_SERVICE_KAFKA_SASL_PASSWORD)"
