apiVersion: v1
kind: Secret
metadata:
  name: rolemapper-service
type: Opaque
stringData:
  s3-bucket-name: "$(AWS_S3_BUCKET_NAME_CONFIG_MAP)"
  s3-aws-access-key-id: "$(S3_AWS_ACCESS_KEY_ID)"
  s3-aws-secret-access-key: "$(S3_AWS_SECRET_ACCESS_KEY)"