---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s-janitor
  name: k8s-janitor
  namespace: $(kubernetes-namespace)
spec:
  ports:
    - name: external
      port: 80
      targetPort: web
  selector:
    app: k8s-janitor
  type: ClusterIP
